/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Domain.Vehicle;
import File.VehicleFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class insertVehicle extends javax.swing.JFrame {

    /**
     * Creates new form insertVehicle
     */
    public insertVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfd_year = new javax.swing.JTextField();
        tfd_name = new javax.swing.JTextField();
        tfd_mileage = new javax.swing.JTextField();
        tfd_series = new javax.swing.JTextField();
        btn_insertVehicle = new javax.swing.JButton();
        btn_listVehicles = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_mileage = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        lbl_american = new javax.swing.JLabel();
        lbl_series = new javax.swing.JLabel();
        cb_american = new javax.swing.JComboBox<>();
        btn_maintenance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_insertVehicle.setText("Insertar");
        btn_insertVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertVehicleActionPerformed(evt);
            }
        });

        btn_listVehicles.setText("Lista Vehiculos");
        btn_listVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listVehiclesActionPerformed(evt);
            }
        });

        lbl_name.setText("Nombre");

        lbl_mileage.setText("Kilometraje");

        lbl_year.setText("Año");

        lbl_american.setText("Americano");

        lbl_series.setText("Serie");

        cb_american.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cb_american.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_americanActionPerformed(evt);
            }
        });

        btn_maintenance.setText("Maintenimiento");
        btn_maintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maintenanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_series, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_american, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_name)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_mileage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfd_series, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(tfd_mileage, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(tfd_year))
                                .addComponent(tfd_name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_american, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_insertVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_listVehicles)
                        .addGap(32, 32, 32)
                        .addComponent(btn_maintenance)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(tfd_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_year))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mileage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_american)
                    .addComponent(cb_american, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_series))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertVehicle)
                    .addComponent(btn_listVehicles)
                    .addComponent(btn_maintenance))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertVehicleActionPerformed
        // TODO add your handling code here:
        Boolean selected=null;
        try{
         try{
             //creando el  archivo
             
            File file= new File("./vehicle.dat");
            VehicleFile vehicleFile = new VehicleFile(file);
            
            //captura los datos del tex field
            
            String nameV= tfd_name.getText();
            int yearV= Integer.parseInt(tfd_year.getText());
            float mileageV= Float.parseFloat(tfd_mileage.getText());
            if((cb_american.getSelectedItem().toString()).equals("Si"))
                selected=true;
            else if((cb_american.getSelectedItem().toString()).equals("No"))
                selected=false; 
            boolean americanV= selected;
            int seriesV= Integer.parseInt(tfd_series.getText());
            
            //aqui se inserta el vehiculo
            
            
            Boolean find_series=false;
            Vehicle vehiculo = new Vehicle(nameV, yearV, mileageV, americanV, seriesV);
            VehicleFile fileVehicle=new VehicleFile(file);
            ArrayList<Vehicle> myArrayVehicles=fileVehicle.getVehicleList();
            for (int i = 0; i <myArrayVehicles.size(); i++) {
                Vehicle temp=myArrayVehicles.get(i);
                if(temp.getSeries()==seriesV){
                find_series=true;
                }//end if
      
            }//end for 
            if(find_series==false && seriesV>=0)
                vehicleFile.addEndRecord(vehiculo);
            else{
                JOptionPane.showMessageDialog(null, "La serie ingresada es invalida");
                tfd_series.setText("");
            }//end else
                
            
          
            // aqui se reseta los texfields
            tfd_name.setText("");
            tfd_year.setText("");
            tfd_mileage.setText("");
            tfd_series.setText("");
                
            
            
            
        }catch(IOException ioe){
             System.out.println("");
        }
         
        }catch(NumberFormatException nme){
        JOptionPane.showMessageDialog(null, "Por favor llene todos los espacios en blanco");
        }
        
    }//GEN-LAST:event_btn_insertVehicleActionPerformed

    
    
    private void btn_listVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listVehiclesActionPerformed
        viewVehicle vehicleView = new viewVehicle();
        vehicleView.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_listVehiclesActionPerformed

    private void cb_americanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_americanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_americanActionPerformed

    private void btn_maintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maintenanceActionPerformed
        // TODO add your handling code here:
        try{
        updateVehicle up= new updateVehicle();
        up.setVisible(true);
        this.setVisible(false);
        }catch(IOException ioe){
        
        }
        
    }//GEN-LAST:event_btn_maintenanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertVehicle().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_insertVehicle;
    private javax.swing.JButton btn_listVehicles;
    private javax.swing.JButton btn_maintenance;
    private javax.swing.JComboBox<String> cb_american;
    private javax.swing.JLabel lbl_american;
    private javax.swing.JLabel lbl_mileage;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_series;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JTextField tfd_mileage;
    private javax.swing.JTextField tfd_name;
    private javax.swing.JTextField tfd_series;
    private javax.swing.JTextField tfd_year;
    // End of variables declaration//GEN-END:variables
}
