/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Domain.Vehicle;
import File.VehicleFile;
import java.io.File;
import java.io.IOError;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class updateVehicle extends javax.swing.JFrame {

    /**
     * Creates new form updateVehicle
     */
    
     File file= new File("./vehicle.dat");
     VehicleFile fileVehi= new VehicleFile(file);
     ArrayList<Vehicle> arraydeVehicle= fileVehi.getVehicleList();
     
    public updateVehicle()throws IOException {
        initComponents();
        tfd_mileage.setEditable(false);
        cb_american.setEnabled(false);
        tfd_name1.setEditable(false);
        tfd_year.setEditable(false);
        btn_delete.setEnabled(false);
        btn_updated.setEnabled(false);
     
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfd_searchSeries = new javax.swing.JTextField();
        lbl_information = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        tfd_mileage = new javax.swing.JTextField();
        lbl_año = new javax.swing.JLabel();
        tfd_name1 = new javax.swing.JTextField();
        lbl_año1 = new javax.swing.JLabel();
        tfd_year = new javax.swing.JTextField();
        lbl_american = new javax.swing.JLabel();
        cb_american = new javax.swing.JComboBox<>();
        btn_updated = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfd_searchSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_searchSeriesActionPerformed(evt);
            }
        });

        lbl_information.setText("Ingrese la serie del Vehiculo");

        lbl_name.setText("Nombre");

        tfd_mileage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_mileageActionPerformed(evt);
            }
        });

        lbl_año.setText("Año");

        tfd_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_name1ActionPerformed(evt);
            }
        });

        lbl_año1.setText("Kilometraje");

        tfd_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_yearActionPerformed(evt);
            }
        });

        lbl_american.setText("Americano");

        cb_american.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        btn_updated.setText("Actualizar");
        btn_updated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatedActionPerformed(evt);
            }
        });

        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_return.setText("Volver");
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfd_name1)
                                .addGap(26, 26, 26)
                                .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfd_searchSeries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_information, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lbl_año, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_año1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_american, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(108, 108, 108))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfd_mileage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_american, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_updated)
                        .addGap(38, 38, 38)
                        .addComponent(btn_delete)
                        .addGap(41, 41, 41)
                        .addComponent(btn_return)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_information)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfd_searchSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_año)
                        .addComponent(lbl_año1)
                        .addComponent(lbl_american)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_american, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updated)
                    .addComponent(btn_delete)
                    .addComponent(btn_return))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfd_searchSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_searchSeriesActionPerformed
        // TODO add your handling code here:
        try{   
       
        Boolean acces=false;
        String comparador= tfd_searchSeries.getText();
        ArrayList<Vehicle> arraydeVehicle= fileVehi.getVehicleList();
        for (int i = 0; i <arraydeVehicle.size(); i++) {
            if(!arraydeVehicle.get(i).getName().equalsIgnoreCase("delete")){
            Vehicle temp= arraydeVehicle.get(i);
            String valor= ""+temp.getSeries();
            acces=true;
                if(valor.equalsIgnoreCase(comparador)){
                    
                    tfd_searchSeries.setEditable(false);
                    tfd_name1.setText(temp.getName());
                    tfd_mileage.setText(Float.toString(temp.getMileage()));
                    tfd_year.setText(Integer.toString(temp.getYear()));
                    cb_american.setEnabled(true);
                    tfd_name1.setEditable(true);
                    tfd_year.setEditable(true);
                    btn_delete.setEnabled(true);
                    btn_updated.setEnabled(true);
                    
            
            
            }
                
        }
            

        }//fin for
        if(acces==false){
            JOptionPane.showMessageDialog(null, "Serie es inexistente");
            tfd_searchSeries.setText("");
        }
        
        }catch(IOException ioe){
        
        JOptionPane.showMessageDialog(null, "Error-1001");
        
        }
       
       
        
        
        
    }//GEN-LAST:event_tfd_searchSeriesActionPerformed

    private void tfd_mileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_mileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_mileageActionPerformed

    private void tfd_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_name1ActionPerformed

    private void tfd_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_yearActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        // TODO add your handling code here:
        insertVehicle in= new insertVehicle();
        in.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_btn_returnActionPerformed

    private void btn_updatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatedActionPerformed
        // TODO add your handling code here:

        
        //aqui recorro todo el array de vehiculos, si encuentra la serie que desea da opciones de actualizar o borrar 
        try{
        Vehicle vehicleTemp;
        for (int i = 0; i < arraydeVehicle.size(); i++) {
            vehicleTemp = arraydeVehicle.get(i) ;
            int series=Integer.parseInt(tfd_searchSeries.getText());
            if(vehicleTemp.getSeries()==series){
                Vehicle vehicleToInsert= new Vehicle(tfd_name1.getText(),Integer.parseInt(tfd_year.getText()), Float.parseFloat(tfd_mileage.getText()), Boolean.parseBoolean(cb_american.getSelectedItem().toString()), Integer.parseInt(tfd_searchSeries.getText()));
                 fileVehi.putValue(i, vehicleToInsert);
                 
                
                 
            }//end if
        }//end for
        tfd_searchSeries.setText("");
        tfd_mileage.setText("");
        tfd_name1.setText("");
        tfd_year.setText("");
        
         tfd_mileage.setEditable(false);
        cb_american.setEnabled(false);
        tfd_name1.setEditable(false);
        tfd_year.setEditable(false);
        btn_delete.setEnabled(false);
        btn_updated.setEnabled(false);
        tfd_searchSeries.setEditable(true);
        
        }catch(IOException ioe){
            System.out.println("Error 1000-3");
        }
        
        
    }//GEN-LAST:event_btn_updatedActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        File file= new File("./vehicle.dat");
        try{
        VehicleFile fileVehicle= new VehicleFile(file);
        Vehicle vehicleTemp;
       
        for (int i = 0; i < arraydeVehicle.size(); i++) {
            vehicleTemp = arraydeVehicle.get(i) ;
            
            int series=Integer.parseInt(tfd_searchSeries.getText());
            if(vehicleTemp.getSeries()==series){
                 vehicleTemp.setName("delete");
                 Vehicle vehicleToInsert= new Vehicle(vehicleTemp.getName(),vehicleTemp.getYear(), vehicleTemp.getMileage(), vehicleTemp.getisAmerican(), -1);
                 fileVehicle.putValue(i, vehicleToInsert);
                 
            }//end if
        }//end for
        //borra los caracteres de los campos de texto
        }catch(IOException ioe){
        
        }
        tfd_searchSeries.setText("");
        tfd_mileage.setText("");
        tfd_name1.setText("");
        tfd_year.setText("");
        
         tfd_mileage.setEditable(false);
        cb_american.setEnabled(false);
        tfd_name1.setEditable(false);
        tfd_year.setEditable(false);
        btn_delete.setEnabled(false);
        btn_updated.setEnabled(false);
        tfd_searchSeries.setEditable(true);
     
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try{
                new updateVehicle().setVisible(true);
                }catch(IOException ioe){
                JOptionPane.showMessageDialog(null, "Falta-1002");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_return;
    private javax.swing.JButton btn_updated;
    private javax.swing.JComboBox<String> cb_american;
    private javax.swing.JLabel lbl_american;
    private javax.swing.JLabel lbl_año;
    private javax.swing.JLabel lbl_año1;
    private javax.swing.JLabel lbl_information;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField tfd_mileage;
    private javax.swing.JTextField tfd_name1;
    private javax.swing.JTextField tfd_searchSeries;
    private javax.swing.JTextField tfd_year;
    // End of variables declaration//GEN-END:variables
}
